### ISSUE TITLE
The percent numbers display has issue

### ISSUE THREAD

**Issue by objczl** [zats/PreciseCoverage#2]
<img width="375" alt="screen shot 2015-11-28 at 11 33 43 am" src="https://cloud.githubusercontent.com/assets/4112633/11449909/05b85e3e-95c4-11e5-9902-82297936cb0e.png">

when scroll down/up will show this.

**Comment by zats** [comment]
great, thanks, I'll take a look at it soon!

**Comment by zats** [comment]
@objczl please give this version a try
Let me know if the issue still persists
Thank you for reporting :rocket:

**Comment by objczl** [comment]
OK, fixed 

Thanks!

**Comment by zats** [comment]
Thanks for reporting 🍰
