### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jkyin** [zats/PreciseCoverage#3]
Can you tell us how to use it?

**Comment by objczl** [comment]
Just enable test target coverage.
<img width="858" alt="screen shot 2015-11-30 at 4 22 49 pm" src="https://cloud.githubusercontent.com/assets/4112633/11466799/bfe2ccf2-977e-11e5-8010-cfc6f65faf6e.png">

**Comment by jkyin** [comment]
Got it. Thank you!
