### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by bixbarton** [zats/PreciseCoverage#6]
Hi - how do I install/use this?

**Comment by zats** [comment]
Hi, sorry for the late response. The easiest way would be to find it in Alcatraz - Xcode plugin manager http://alcatraz.io
Once installed just search for `PreciseCoverage`
Alternatively, download and build the project, once build finished restart Xcode (it installs the plugin as a part of the build process).
Hope that helps

**Comment by zats** [comment]
I'm closing the issue for now, feel free to reopen it if you still have any questions
