### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by dimohamdy** [zats/PreciseCoverage#7]
@zats  please update readme.md to show how we can use it ?

**Comment by zats** [comment]
Hi,
to be honest there is not much more I can add to readme, the image ![](https://github.com/zats/PreciseCoverage/raw/master/screenshot.png) shows what your standard coverage interface will look like once you install the plugin and if you are familiar with original coverage interface, this should be fairly straight forward. 

As readme states, I just made sure the percentage is clearly indicated in text + various colours are assigned to further indicate the threshold of each coverage.

Do you have any particular question or suggestions so I can understand better what's unclear in the current readme?

Thanks!

**Comment by dimohamdy** [comment]
thanks

**Comment by dimohamdy** [comment]
thanks
